Add support for embedded iframe
Sonat-Consulting/b3 pull request #6
Opened 2022-06-17 20:53 UTC by mathiash98

Goal: Add support for embedding IFrame in articles in order to render the interactive map.

Added content model in Contentful for IFrame:
![image](https://user-images.githubusercontent.com/5204006/174398495-9a937b04-9080-4820-80e9-8f7bca036162.png)

To use:
1. Add new content with contentType `IFrame`
![image](https://user-images.githubusercontent.com/5204006/174398759-8c9fc5aa-1146-4b83-a8bc-78ddee956058.png)
2. Edit article and click "Embed" -> "Entry" -> Select an IFrame entry
![image](https://user-images.githubusercontent.com/5204006/174398589-c1a08803-7df0-4631-bee3-4d26812bc4d1.png)

Demo of embedded map:
https://user-images.githubusercontent.com/5204006/174398406-4bbe1d0d-5876-4ab4-a931-1e2175162414.mp4

2022-06-20 19:56 UTC, jonalu requested changes
Thanks for your contribution. I have provided some feedback in the comments, please address these. As we haven't provided a style guide it is understandable that some code styles deviates a bit from the our standard.

2022-06-20 19:56 UTC, jonalu commented on README.md
> +Frontend is written in Svelte with content being served from a ContentFul backend, currently at https://app.contentful.com/spaces/wi3d49ltoppx
Please avoid publishing the Contentful space ID.

2022-06-20 19:56 UTC, jonalu commented on README.md
> +VITE_CONTENTFUL_SPACE_ID=wi3d49ltoppx
Omit the space ID. You could use a placeholder instead.

2022-06-20 19:56 UTC, jonalu commented on src/lib/contentful/types/Article.ts
> +	} | null;
The ` | null ` here seems superfluous as you've configured as `articleHeroImage? : { }`

2022-06-20 19:56 UTC, jonalu commented on src/routes/news/[slug].svelte
>          />
It is best not to render the image element altogether if the `url` property is `undefined`.

2022-06-20 19:56 UTC, jonalu commented on src/routes/news/[slug].svelte
> +                        return "nothing";
Remove all debug logging. Also returning the string `"nothing"` makes no sense. It is better to return empty.

2022-06-20 19:56 UTC, jonalu commented on src/routes/news/[slug].svelte
> +                            >Det ser ut til den innebygde iframen ikke ble lastet inn, prøv igjen senere eller kontakt sideadministrator.</iframe>
Omit the fallback text. It does not give the user any valuable information. Also, there is no way for the user to contact the site administrator.

2022-06-20 19:56 UTC, jonalu commented on src/routes/news/[slug].svelte
> +                                title="${(entry as IFrameEntry).title}"
Try to follow the DRY principle and avoid casting the `entry` to `IFrameEntry` more than once.

2022-06-20 19:56 UTC, jonalu commented on src/routes/news/[slug].svelte
> +                    // https://www.contentful.com/blog/2021/04/14/rendering-linked-assets-entries-in-contentful/
This comment provides some value as it refers to relevant documentation. All other comments should be removed. We should strive to keep the code self documented through proper naming conventions.

2022-06-20 19:56 UTC, jonalu commented on src/lib/news.svelte
> +			imageSrc={article.articleHeroImage?.url}
How would the `<ArticleLink />` component handle missing `imageSrc`. Now that you've made this field optional, this scenario needs to be handled.

2022-06-21 16:00 UTC, jonalu commented on src/lib/contentful/types/Article.ts
> +	} | null;
Ok, remove the `?`

2022-06-21 18:33 UTC, jonalu reviewed
I would like to get your take on how you plan on making the iframe work in a responsive layout.

2022-06-22 07:21 UTC, mathiash98 commented on src/routes/news/[slug].svelte
> +                                width="${iframeEntry.width}"
That method will not create a general responsive iframe as you assume the aspect ratio of the content. The map we are embedding is a website which is responsive by itself.

In general it's always hard to insert content that catches touch input into websites as the user can be stuck in that area. 
- So the important thing is to keep some margin on the sides to enable scrolling if the height of the screen is smaller than the height of the content.

Screenshot is of iPhone SE:
![image](https://user-images.githubusercontent.com/5204006/174968438-bfc16f1c-0b67-4b1c-9358-654290c345b6.png)
iPhone 12 pro:
![image](https://user-images.githubusercontent.com/5204006/174968506-fb637079-3509-4fab-adf2-14c2b19f9379.png)

2022-06-22 07:22 UTC, mathiash98 commented
> I have approved the Netlify preview release so that we can see the changes live.

Connected to another backend?

2022-06-26 15:01 UTC, jonalu commented
> > I have approved the Netlify preview release so that we can see the changes live.
> 
> Connected to another contentful CMS backend?

Good question. Actually no. I have added support for Contenful draft content in Netlify preview-deploys:
https://github.com/Sonat-Consulting/b3/pull/7

If you update your PR with the `main` branch you should be able to add draft content in Contenful and view them in the Netlify preview deployment as seen [here](https://deploy-preview-7--bergen3.netlify.app/).

2022-06-27 14:36 UTC, jonalu commented
Super. It looks good. For the future, try to avoid merge commits and rather rebase your changes on top of the `main` branch. That allows us to rebase the PRs.

2022-06-27 14:37 UTC, merged